export const SUBJECTS = [
  "Mathematics",
  "Combined Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "ICT",
  "Science",
  "Science for Technology",
  "English",
  "Sinhala",
  "Tamil",
  "Buddhism",
  "History",
  "Geography",
  "Economics",
  "Business Studies",
  "Accounting",
  "Commerce",
  "Art",
  "Music",
  "Dancing",
  "Drama and Theater",
  "Political Science",
  "Sociology",
  "Logic",
  "French",
  "Japanese",
  "Korean",
  "Arabic",
  "Hindi",
  "German",
  "Engineering Technology",
  "Agricultural Science",
  "Home Science",
  "Health & Physical Education",
  "Computer Science",
  "Information Technology",
  "Communication & Media Studies",
  "IELTS",
  "Spoken English",
  "Other",
] as const;

export const GRADES = [
  "Grade 1-5",
  "Grade 6-9",
  "Grade 10-11",
  "O/L (Local)",
  "O/L (International)",
  "A/L (Local)",
  "A/L (International)",
  "Degree / Diploma",
  "Professional",
  "All Grades",
] as const;

export const DISTRICTS = [
  "All Island",
  "Colombo",
  "Gampaha",
  "Kalutara",
  "Kandy",
  "Matale",
  "Nuwara Eliya",
  "Galle",
  "Matara",
  "Hambantota",
  "Jaffna",
  "Kilinochchi",
  "Mannar",
  "Mullaitivu",
  "Vavuniya",
  "Trincomalee",
  "Batticaloa",
  "Ampara",
  "Kurunegala",
  "Puttalam",
  "Anuradhapura",
  "Polonnaruwa",
  "Badulla",
  "Monaragala",
  "Ratnapura",
  "Kegalle",
] as const;

export const CLASS_TYPES = [
  "Online",
  "Physical",
  "Home Visit",
  "Group",
  "Individual",
] as const;

/** Home sticky bar + listing filter chips (value matches ad `grade` field). */
export const BROWSE_GRADE_OPTIONS = [
  { label: "O/L Classes", value: "O/L (Local)" },
  { label: "A/L Classes", value: "A/L (Local)" },
  { label: "Grade 6-11", value: "Grade 6-9" },
  { label: "Grade 1-5", value: "Grade 1-5" },
] as const;

export type Subject = (typeof SUBJECTS)[number];
export type Grade = (typeof GRADES)[number];
export type District = (typeof DISTRICTS)[number];
export type ClassType = (typeof CLASS_TYPES)[number];
